const VIEW_ITEM_STATE = "VIEW_ITEM_STATE";
const INCREMENT_CART_AND_ADD_OBJECT = "INCREMENT_CART_AND_ADD_OBJECT";
const UPDATE_SELECTED_ITEM = "UPDATE_SELECTED_ITEM";
const UPDATE_SELECTED_ITEM_EXTRAS = "UPDATE_SELECTED_ITEM_EXTRAS";
const UPDATE_FLAVOURS = "UPDATE_FLAVOURS";
export {
  VIEW_ITEM_STATE,
  INCREMENT_CART_AND_ADD_OBJECT,
  UPDATE_SELECTED_ITEM,
  UPDATE_SELECTED_ITEM_EXTRAS,
  UPDATE_FLAVOURS
};
